Turotial 1: initialize and use the FlexMol encoders to transform raw molecular data into meaningful representations.

In [2]:
import os
os.chdir('../')

from FlexMol.encoder import *

In [3]:
# The Encoder class in FlexMol transforms raw molecular data through preprocessing and encoding.

# Method 1: Direct initialization
cnn_encoder = DrugEncoder("CNN")

# Method 2: Using FlexMol
BE = FlexMol()
cnn_encoder = BE.init_drug_encoder("CNN", filters=[32, 64, 96]) # optional customized initialization

In [6]:
# Each encoder has a `featurizer` and a `model`.
# Get the featurizer and model
featurizer = cnn_encoder.get_featurizer()
encoder_layer = cnn_encoder.get_model()

In [5]:
# The Featurizer preprocess raw data into a model-readable format
drug = "CCO"
processed_data = featurizer(drug)
print(processed_data)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
# The model serves as a building block layer of the MRL model.
# For demonstration, we convert processed data to a tensor and add batch dimension
processed_tensor = torch.tensor(processed_data).float().unsqueeze(0)
output = encoder_layer(processed_tensor)
print("Sample Layer Output:", output)


Sample Layer Output: tensor([[-9.3898e-02,  1.4590e-02,  7.9865e-02, -2.1684e-02,  9.1860e-02,
         -4.2191e-03, -2.7984e-02,  2.2402e-02, -3.6640e-02, -3.9994e-02,
          5.9961e-02, -6.1900e-02,  7.3785e-02, -4.0451e-03, -1.7991e-02,
         -2.9744e-02,  8.1293e-02, -2.5096e-02, -3.8066e-02, -1.0186e-03,
         -6.4144e-02, -1.3440e-02, -3.2163e-03, -4.6644e-02, -1.0421e-01,
         -1.1971e-02, -2.6323e-02,  9.1197e-02, -5.5418e-02,  6.3180e-02,
          3.1857e-02, -4.0757e-02, -7.9065e-02, -9.6381e-02,  6.3246e-02,
         -9.5012e-02,  8.3901e-02, -1.7794e-02, -1.0899e-01,  6.3650e-02,
         -8.4964e-02, -5.4495e-02, -3.7407e-02,  2.9002e-03, -3.2082e-02,
          2.0454e-02, -6.8078e-02,  2.6614e-02, -8.2436e-03,  5.2349e-02,
         -9.6675e-02, -1.0055e-04, -7.4656e-03, -1.2686e-02, -8.1079e-02,
          2.7542e-02,  2.2552e-02,  7.3664e-02, -7.8480e-02,  4.5978e-02,
          2.1238e-02,  1.0284e-02,  8.6597e-03, -6.5687e-02,  7.4655e-02,
          7.2822e